docs: add zone_name and zone_id to readme
cloudposse/terraform-aws-acm-request-certificate pull request #67
Opened 2023-03-03 13:40 UTC by nitrocode

## what
* add zone_name and zone_id to readme

## why
* show how to use the module and be explicit about the zone to add validation records to

## references
- Previous PR #62
- Related issue https://github.com/cloudposse/terraform-aws-acm-request-certificate/issues/62
- Related draft pr https://github.com/cloudposse/terraform-aws-acm-request-certificate/pull/63
- Related pr #66

2023-04-30 19:47 UTC, acorncom commented
It'd be handy to have info about the zone options higher up in the readme, any chance we can get this merged?

2023-04-30 19:47 UTC, acorncom approved these changes

2024-02-27 19:06 UTC, Nuru requested changes
After #66, this is no longer accurate. Subject alternative names are not considered when trying to determine Zone.

2024-03-06 22:35 UTC, hans-d commented
@Nuru @nitrocode can we close this pr (given the latest remark)? if not, it will be closed soon if the pr does not get any sensible update.

2024-03-10 13:21 UTC, closed without merging